version: '3'

services:
  
  dafpi:
    build: 
      context: ./daf-pi
      dockerfile: Dockerfile
    container_name: dafpi
    entrypoint: socat -d -d pty,raw,echo=0 pty,raw,echo=0
    networks:
      - dafpi-network
    ports:
      - 9000:80

networks:
  dafpi-network:
    driver: bridge